{% set name = "array-api-strict" %}
{% set version = "2.6.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 27485fd687c678894fb193e8f9f5116651a0bfc19dccea164d7d5df83b4e9a82

build:
  number: 0
  # This stays as noarch as it's a test dependency: https://github.com/AnacondaRecipes/array-api-strict-feedstock/pull/2#discussion_r1819058071
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation  

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools >=61.0,<=75
    - setuptools_scm >8,<10
  run:
    - python >=3.10
    - numpy

test:
  imports:
    - array_api_strict
  commands:
    - pip check
    - pytest --pyargs array_api_strict
  requires:
    - pip
    - pytest
    - hypothesis

about:
  home: https://github.com/data-apis/array-api-strict
  summary: A strict, minimal implementation of the Python array API standard.
  description: |
    array_api_strict is a strict, minimal implementation of the Python array API.
    The purpose of array-api-strict is to provide an implementation of the array API 
    for consuming libraries to test against so they can be completely sure their usage 
    of the array API is portable.
    It is not intended to be used by end-users. End-users of the array API should just 
    use their favorite array library (NumPy, CuPy, PyTorch, etc.) as usual. 
    It is also not intended to be used as a dependency by consuming libraries. 
    Consuming library code should use the array-api-compat package to support the array API. 
    Rather, it is intended to be used in the test suites of consuming libraries to test their array API usage.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/data-apis/array-api-strict
  doc_url: https://data-apis.org/array-api-strict

extra:
  skip-lints:
    - avoid_noarch
  recipe-maintainers:
    - asmeurer
    - rgommers
